language: rust
cache: cargo

rust:
  - 1.34.0
  - nightly

script:
  - cd $TRAVIS_BUILD_DIR/arcs
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose

before_deploy:
  - cd $TRAVIS_BUILD_DIR/arcs
  - cargo doc --verbose
  - echo '<meta http-equiv="refresh" content="0; url=arcs/index.html" /> ' > target/doc/index.html
  - cp -r target/doc $TRAVIS_BUILD_DIR/public

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/public
  on:
    branch: master
    rust: nightly
