language: rust
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/arcs/target
    - $TRAVIS_BUILD_DIR/demo/target

rust:
  # Required for #[non_exhaustive]
  - 1.40.0
  - nightly

install:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - command -v cargo-make >/dev/null 2>&1 || cargo install cargo-make
  - set -e

script:
  - cd $TRAVIS_BUILD_DIR/arcs
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - cd $TRAVIS_BUILD_DIR/demo
  - cargo build --verbose
  - cargo make build_release

before_deploy:
  - cd $TRAVIS_BUILD_DIR/arcs
  - cargo doc --verbose
  - echo '<meta http-equiv="refresh" content="0; url=arcs/index.html" /> ' > target/doc/index.html
  - cp -r target/doc $TRAVIS_BUILD_DIR/public

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/public
  on:
    branch: master
    rust: nightly
