language: rust
cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/arcs/target
    - $TRAVIS_BUILD_DIR/demo/target

rust:
  # Required for #[non_exhaustive]
  - 1.40.0
  - nightly

install:
  - export PATH="$HOME/.cargo/bin:$PATH"
  - command -v wasm-pack >/dev/null 2>&1 || cargo install wasm-pack
  - set -e

script:
  - cd $TRAVIS_BUILD_DIR/arcs
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
  - cd $TRAVIS_BUILD_DIR/demo
  - cargo build --verbose
  - wasm-pack build --dev --target web

before_deploy:
  # prepare API docs
  - cd $TRAVIS_BUILD_DIR/arcs
  - cargo doc --verbose
  - echo '<meta http-equiv="refresh" content="0; url=arcs/index.html" /> ' > target/doc/index.html
  # then copy the docs to the public/crate_docs/ directory
  - cd $TRAVIS_BUILD_DIR
  - mkdir public
  - cp -r arcs/target/doc public/crate_docs/
  # do the same for the WebAssembly demo
  - tree demo -I target
  - mkdir public/demo/
  - cp demo/index.html public/demo/
  - cp -r demo/pkg/ public/demo/pkg/
  # going to the root GitHub Pages page should show the demo
  - echo '<meta http-equiv="refresh" content="0; url=demo/index.html" /> ' > public/index.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/public
  on:
    branch: master
    rust: nightly
