[package]
name = "arcs"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
edition = "2018"
description = "Facade crate for the arcs CAD library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arcs-core = { path = "../core" }
arcs-render = { path = "../render" }
